/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 * Pantalla para la creacion de macrociclos
 * @author ldoar
 */
public class crearMacrocicloFrm extends javax.swing.JFrame {

    //boolean que almacena si el macrociclo es valido
    boolean macrocicloVaiido = false;
    //entero que almacena el total de semanas de un macrociclo
    int totalSemanas;

    /**
     * Metodo constructor que inicializar los componentes de la pantalla
     */
    public crearMacrocicloFrm() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtTotalSemanas1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jpPanel1 = new javax.swing.JPanel();
        jdcFechaInicio = new com.toedter.calendar.JDateChooser();
        jdcFechaFin = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtTotalSemanas = new javax.swing.JTextField();
        jbtnCalcular = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jtxtTotalDias = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jbtnCrearMacrociclo = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();
        jlbSalir = new javax.swing.JLabel();

        jtxtTotalSemanas1.setEditable(false);

        jLabel9.setText("Total de semanas: ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Macrociclo");
        setResizable(false);

        jpPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jpPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jdcFechaInicio.setDateFormatString("dd/MM/yyyy");

        jdcFechaFin.setDateFormatString("dd/MM/yyyy");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nuevo Macrociclo");

        jLabel2.setText("Ingrese fecha de inicio");

        jLabel3.setText("Ingrese fecha de fin");

        jLabel4.setText("Total de semanas: ");

        jtxtTotalSemanas.setEditable(false);
        jtxtTotalSemanas.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jbtnCalcular.setBackground(new java.awt.Color(204, 204, 255));
        jbtnCalcular.setText("Calcular semanas");
        jbtnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCalcularActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Disciplina");

        jtxtTotalDias.setEditable(false);
        jtxtTotalDias.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel10.setText("Total de dias: ");

        jbtnCrearMacrociclo.setBackground(new java.awt.Color(204, 255, 204));
        jbtnCrearMacrociclo.setText("Crear macrociclo");
        jbtnCrearMacrociclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCrearMacrocicloActionPerformed(evt);
            }
        });

        jbtnCancelar.setBackground(new java.awt.Color(255, 102, 102));
        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });

        jlbSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/salir.png"))); // NOI18N
        jlbSalir.setToolTipText("");
        jlbSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbSalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpPanel1Layout = new javax.swing.GroupLayout(jpPanel1);
        jpPanel1.setLayout(jpPanel1Layout);
        jpPanel1Layout.setHorizontalGroup(
            jpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(39, 39, 39)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPanel1Layout.createSequentialGroup()
                        .addGroup(jpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdcFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(jpPanel1Layout.createSequentialGroup()
                                .addGroup(jpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel4))
                                .addGap(34, 34, 34)
                                .addGroup(jpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtTotalSemanas, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtTotalDias, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jbtnCalcular))
                        .addGap(50, 50, 50)
                        .addGroup(jpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jdcFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpPanel1Layout.createSequentialGroup()
                                .addComponent(jbtnCrearMacrociclo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(jpPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbSalir)
                .addGap(35, 35, 35))
        );
        jpPanel1Layout.setVerticalGroup(
            jpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlbSalir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jdcFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdcFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jtxtTotalDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jtxtTotalSemanas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addGroup(jpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCrearMacrociclo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Evento que calcula la cantidad de semanas de un macrociclo al presionar
 * el boton calcular macrociclo
 * @param evt 
 */
    private void jbtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCalcularActionPerformed
        //establece el total de semanas y dias a 0
        this.jtxtTotalSemanas.setText("0");
        this.jtxtTotalDias.setText("0");

        //crea 3 variables una para la fecha actual no definida, una para la fecha inicio nula y otra para la fecha fin nula
        LocalDate fechaActual, fechaInicio = null, fechaFin = null;
        //obtiene la fecha de inicio ingresada por el usuario y lo guarda en la variable
        Date fechaElegidaInicio = jdcFechaInicio.getDate();
        //obtiene la fecha de inicio ingresada por el usuario y lo guarda en la variable
        Date fechaElegidaFin = jdcFechaFin.getDate();
        //instancia localdate con la fecha actual
        fechaActual = LocalDate.now();

        if (fechaElegidaInicio == null) {
            //si la fecha elegida de inicio es nula muestra un mensaje de error indicando
            JOptionPane.showMessageDialog(this, "Error. Ingrese fecha de inicio.");
        } else {
            //crea un date time formatter
            DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");

            //convierte la fecha a un instant y se ajusta a la zona horaria actual del sistema
            fechaInicio = fechaElegidaInicio.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

            //le da el formato a la fecha 
            String fechaInicioFormateada = formato.format(fechaInicio);

            //imprime la fecha ingresada y la fecha formateada
            System.out.println(fechaInicio);
            System.out.println(fechaInicioFormateada);
        }

        
        if (fechaElegidaFin == null) {
            //si la fecha final elegida es nula muestra un mensaje de error
            JOptionPane.showMessageDialog(this, "Error. Ingrese fecha de inicio.");
        } else {
            //crear un formato para la fecha
            DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");

            //convierte la fecha a un instant y se ajusta a la zona horaria actual del sistema
            fechaFin = fechaElegidaFin.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

            //le da el formato a la fecha 
            String fechaFinFormateada = formato.format(fechaFin);

            //imprime la fecha ingresada y la fecha formateada
            System.out.println(fechaFin);
            System.out.println(fechaFinFormateada);
        }

        if (fechaInicio != null && fechaFin != null) {
            //si las fechas ingresadas no son nulas
            //calcula los dias entre las fechas ingresadas
            long diasEntreFechas = ChronoUnit.DAYS.between(fechaInicio, fechaFin);
            //se asignan al jtxt los dias totales
            this.jtxtTotalDias.setText(Long.toString(diasEntreFechas));

            
            if (fechaInicio.equals(fechaFin)) {
                //si la fecha de inicio y la fecha fin son iguales mostrando que son la misma fecha
                JOptionPane.showMessageDialog(this, "Error. La fecha de finalización es igual a la de inicio.");
            }
            if (diasEntreFechas <= 0) {
                //si los dias entre las fechas son iguales a 0 muestra un mensaje de error
                JOptionPane.showMessageDialog(this, "Error. Números totales del macroclico menores o iguales a 0.");
            }
            if (diasEntreFechas % 7 != 0) {
                //si los dias entre las fechas totales no son multiplo de 7 entonces muestra un mensaje de error
                JOptionPane.showMessageDialog(this, "Error. Tienen que ser semanas completas.");
            } else {
                //cambia el macrociclo es valido a true
                macrocicloVaiido = true;
                //calcula las semanas totales entre las fechas ingresadas
                long semanasEntreFechas = ChronoUnit.WEEKS.between(fechaInicio, fechaFin);
                //imprime el total de semanas
                System.out.println("Semanas : " + semanasEntreFechas);

                //le agrega el total de semanas al campo
                this.jtxtTotalSemanas.setText(Long.toString(semanasEntreFechas));
                //cambia el total de semanas a entero
                totalSemanas = (int) semanasEntreFechas;

            }
        }
    }//GEN-LAST:event_jbtnCalcularActionPerformed
/**
 * metodo que se encarga de manejar el evento de crear macrociclo
 * @param evt 
 */
    private void jbtnCrearMacrocicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCrearMacrocicloActionPerformed
        //opciones del menu
        String[] opciones = {"Aceptar", "Cancelar"};
        
        if (macrocicloVaiido) {
            //si el macrociclo es valido
            //obtiene la opciones seleccionada
            int opcion = JOptionPane.showOptionDialog(this, "¿Quieres crear este macrociclo?", "Opciones", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null,
                    opciones, opciones[0]);
            if (opcion == 0) {
                
            }
        } else {
            //si el macrociclo no es valido muestra un mensaje de error
            JOptionPane.showMessageDialog(this, "Error. Macrociclo no válido, se necesita calcular semanas primero.");
        }

    }//GEN-LAST:event_jbtnCrearMacrocicloActionPerformed

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        //muestra las opciones del boton cancelar
        String[] opciones = {"Aceptar", "Cancelar"};

        //obtiene la opcion seleccionada
        int opcion = JOptionPane.showOptionDialog(this, "¿Quieres cancelar la creación del macrociclo?", "Opciones", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null,
                opciones, opciones[0]);

        //si la opcion seleccionada es 0
        if (opcion == 0) {

        } else if (opcion == 1) {
            // Código para la opción "Consultar"
            // Por ejemplo, abrir una ventana para consultar algo.
        }
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    private void jlbSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbSalirMouseClicked
        //muestra las opciones del boton salir
        String[] opciones = {"Aceptar", "Cancelar"};

        //obtiene la opcion seleccionada
        int opcion = JOptionPane.showOptionDialog(this, "¿Quieres regresal al menu principal?", "Opciones", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null,
                opciones, opciones[0]);

        if (opcion == 0) {
            //si selecciona aceptar instancia la pantalla principal
            inicioFrm inicio = new inicioFrm();
            //borra la pantalla actual
            this.dispose();
        } else if (opcion == 1) {
            // Código para la opción "Consultar"
            // Por ejemplo, abrir una ventana para consultar algo.
        }
    }//GEN-LAST:event_jlbSalirMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbtnCalcular;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnCrearMacrociclo;
    private com.toedter.calendar.JDateChooser jdcFechaFin;
    private com.toedter.calendar.JDateChooser jdcFechaInicio;
    private javax.swing.JLabel jlbSalir;
    private javax.swing.JPanel jpPanel1;
    private javax.swing.JTextField jtxtTotalDias;
    private javax.swing.JTextField jtxtTotalSemanas;
    private javax.swing.JTextField jtxtTotalSemanas1;
    // End of variables declaration//GEN-END:variables
}
