/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import javax.swing.JOptionPane;

/**
 *
 * @author ldoar
 */
public class VolumenFrm extends javax.swing.JFrame {

    /**
     * Creates new form VolumenFrm
     */
    public VolumenFrm() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpVolumen = new javax.swing.JPanel();
        jcbDisciplinas = new javax.swing.JComboBox<>();
        bntSeleccionar = new javax.swing.JButton();
        bntEliminar = new javax.swing.JButton();
        jcbDisciplinasSeleccionadas = new javax.swing.JComboBox<>();
        jlbSalir = new javax.swing.JLabel();
        jbGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Volumen");

        jpVolumen.setBackground(new java.awt.Color(255, 255, 255));

        jcbDisciplinas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        bntSeleccionar.setText("Seleccionar");
        bntSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSeleccionarActionPerformed(evt);
            }
        });

        bntEliminar.setText("Eliminar selección");
        bntEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEliminarActionPerformed(evt);
            }
        });

        jlbSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/salir.png"))); // NOI18N

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpVolumenLayout = new javax.swing.GroupLayout(jpVolumen);
        jpVolumen.setLayout(jpVolumenLayout);
        jpVolumenLayout.setHorizontalGroup(
            jpVolumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVolumenLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jpVolumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bntSeleccionar)
                    .addComponent(jcbDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jpVolumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bntEliminar)
                    .addGroup(jpVolumenLayout.createSequentialGroup()
                        .addComponent(jcbDisciplinasSeleccionadas, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 692, Short.MAX_VALUE)
                .addComponent(jlbSalir)
                .addGap(30, 30, 30))
        );
        jpVolumenLayout.setVerticalGroup(
            jpVolumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVolumenLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jpVolumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbSalir)
                    .addGroup(jpVolumenLayout.createSequentialGroup()
                        .addGroup(jpVolumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbDisciplinasSeleccionadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbGuardar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntEliminar))
                    .addGroup(jpVolumenLayout.createSequentialGroup()
                        .addComponent(jcbDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntSeleccionar)))
                .addContainerGap(547, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpVolumen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpVolumen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSeleccionarActionPerformed
        String datoSeleccionado = (String) this.jcbDisciplinas.getSelectedItem();
        this.jcbDisciplinasSeleccionadas.addItem(datoSeleccionado);

        // Oculta el dato seleccionado en el comboBoxOrigen
        int index = this.jcbDisciplinas.getSelectedIndex();
        if (index != -1) {
            this.jcbDisciplinas.removeItemAt(index);
        }
    }//GEN-LAST:event_bntSeleccionarActionPerformed

    private void bntEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEliminarActionPerformed
        if (this.jcbDisciplinasSeleccionadas.getItemCount() == 0) {
            JOptionPane.showMessageDialog(this, "Error. Seleccione disciplinas");
        }
        //Al ser valido el combobox de disciplinas seleccionadas se realizara la eliminacion del campo seleccionado
        else{
            String[] opciones = {"Aceptar", "Cancelar"};
            //obtiene la opcion seleccionada por el usuario
            int opcion = JOptionPane.showOptionDialog(this, "¿Quieres eliminar esa disciplina?:", "Opciones", JOptionPane.DEFAULT_OPTION,  JOptionPane.PLAIN_MESSAGE, null, 
                    opciones, opciones[0]);

            if (opcion == 0) {
                String datoSeleccionado = (String) this.jcbDisciplinasSeleccionadas.getSelectedItem();
                this.jcbDisciplinas.addItem(datoSeleccionado);

                // Elimina el dato seleccionado en el comboBoxDestino
                int index = this.jcbDisciplinasSeleccionadas.getSelectedIndex();
                if (index != -1) {
                    this.jcbDisciplinasSeleccionadas.removeItemAt(index);
                }
            }
        } 
    }//GEN-LAST:event_bntEliminarActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        if (this.jcbDisciplinasSeleccionadas.getItemCount() == 0) {
            JOptionPane.showMessageDialog(this, "Error. Seleccione disciplinas");
        }
        //Al ser valido el combobox de disciplinas seleccionadas se habilitan las tablas para calcular y distribuir el volumen
        else{
            String[] opciones = {"Aceptar", "Cancelar"};
            //obtiene la opcion seleccionada por el usuario
            int opcion = JOptionPane.showOptionDialog(this, "¿Guardar estas disciplinas?:", "Opciones", JOptionPane.DEFAULT_OPTION,  JOptionPane.PLAIN_MESSAGE, null, 
                    opciones, opciones[0]);

            if (opcion == 0) {
                
            }
        }
    }//GEN-LAST:event_jbGuardarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntEliminar;
    private javax.swing.JButton bntSeleccionar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JComboBox<String> jcbDisciplinas;
    private javax.swing.JComboBox<String> jcbDisciplinasSeleccionadas;
    private javax.swing.JLabel jlbSalir;
    private javax.swing.JPanel jpVolumen;
    // End of variables declaration//GEN-END:variables
}
