# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'

    - name: Show JDK location
      run: |
        ls -l /usr/lib/jvm
        echo "JAVA_HOME is: $JAVA_HOME"

    - name: localizar JDK
      run: ant -Dplatforms.JDK_19.home=</opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/19.0.2-7/x64>
        
    - name: Build de negocios
      #env:
       # JAVA_HOME: '/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/19.0.2-7/x64'
        
      run: ant -f polideportivo_negocio/build.xml
      
    #- name: Pruebas unitarias
    #  run: ant test
